[project]
name = "project-automated-customers-reviews"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django==6.0.7",
    "dj-database-url==3.1.2",
    "whitenoise==6.8.2",
    "asgiref==3.12.1",
    "sqlparse==0.5.5",
    "psycopg2-binary==2.9.12",
    "python-dotenv==1.2.2",
    "tzdata==2026.3",
    "httpx==0.28.1"
]

[tool.vercel]
entrypoint = "config.asgi:application"